<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dls210" ignored="2" name="Teste" tests="4" failures="1" timestamp="18 jul 2018 16:36:52 GMT" time="0.068" errors="0">
  <testcase name="String" time="0.012" classname="testclasses.TestNGAssert"/>
  <testcase name="array" time="0.002" classname="testclasses.TestNGAssert"/>
  <testcase name="testeSum" time="0.001" classname="testclasses.TestNGAssert"/>
  <testcase name="testSum" time="0.006" classname="testclasses.TestNGSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [3]
at testclasses.TestNGSoftAssert.testSum(TestNGSoftAssert.java:22)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSum -->
  <testcase name="testMethod2" time="0.0" classname="dependentMethods.DependentMethods">
    <ignored/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod1" time="0.0" classname="dependentMethods.DependentMethods">
    <ignored/>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Teste -->
