<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dls210" ignored="0" name="Teste" tests="6" failures="2" timestamp="18 jul 2018 11:21:15 GMT" time="0.198" errors="0">
  <testcase name="String" time="0.015" classname="testclasses.TestNGAssert"/>
  <testcase name="array" time="0.003" classname="testclasses.TestNGAssert"/>
  <testcase name="testeSum" time="0.004" classname="testclasses.TestNGAssert"/>
  <testcase name="testSum" time="0.012" classname="testclasses.TestNGSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [3]
at testclasses.TestNGSoftAssert.testSum(TestNGSoftAssert.java:22)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSum -->
  <testcase name="testMethod2" time="0.001" classname="dependentMethods.DependentMethods"/>
  <testcase name="testMethod1" time="0.111" classname="dependentMethods.DependentMethods">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method dependentMethods.DependentMethods.testMethod1() didn&amp;apos;t finish within the time-out 100">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method dependentMethods.DependentMethods.testMethod1() didn't finish within the time-out 100
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Teste -->
